### ISSUE TITLE
Splitting Endpoints of Verification Controller

### ISSUE THREAD

**Issue by anjeyy** [corona-warn-app/cwa-verification-server#104]
## Current Implementation

- Currently `VerificationController` has multiple Endpoints which do different things. 

## Suggested Enhancement

- Split content of `VerificationController` into (for example) three different controllers. Naturally seperated by given Endpoints. (**RegistrationTokenController**, **TestresultController**, **TanController**)

## Expected Benefits

- Splitting up gives better encapsulation for different actions beeing performed. (_SRP_)
-  Further it benefits for #60 but even if you keep the package layers it benefits the structure and readybility.

I think it is a good first issue for new people looking forward to contribute. (I know me included. :relaxed:  )

**Comment by f11h** [comment]
Hi @anjeyy,
your request will be implemented in the feat/split-internal-and-external-endpoints branch (c9354341b27cbdae60f11cbbafca750af485aaa6)

**Comment by ascheibal** [comment]
Hi @anjeyy, we finally made this available with version 1.2/1.3 of the verification server. Thanks for contributing.
