### ISSUE TITLE
Controller Verification

### ISSUE THREAD

**Issue by anjeyy** [corona-warn-app/cwa-verification-server#105]
## Current Implementation
I was wondering in `VerificationController` for exceptions to be thrown to let the client know if a ressource is missing or if it was a bad request. 

1. `generateRegistrationToken(...)` - There is a `bad request` thrown after validating the pattern for provided `key` from client.

1. `generateTan(...)` - If no `VerificationAppSession` was found there is a `bad request` - `400` retuned.

1. In generell the exception handling is pretty late in the controller (f.e. `generateTan(...)` ). Additionally there have to be performed many checks.

## Suggested Enhancement

1. Custom constraints to check wheter execution logic should be performed after all. - A first reference see https://www.baeldung.com/spring-mvc-custom-validator

1. It should throw a `not found` - `404` since no `AppSession` could be found. A `bad request` **should** have been thrown if the serverside had a verification process ging on. But since nothing was found in the database there can only be a `404` thrown.

1. Replace validation inside Controller. For example in  `AppSessionService.getAppSessionByToken(...)` with 
```
appSessionRepository.findByRegistrationTokenHash(hashingService.hash(registrationToken))
                    .orElseThrow(() -> new RessourceNotFoundException(...)); 
```
This specific `RessourceNotFoundException` can have a field with the ressource that was not found so it's applicable to other ressources. And more important `RessourceNotFoundException` can be bound in the GlobalExceptionHandler with a proper http status code as it is currently present with other exceptions.

## Expected Benefits

1. Before even a line of code inside the controller is executed, there is a validation of the given GUID, otherwise client gets immediate error.

1. Use of intended ReST architecture with specific http status codes.

1. Not validating in the controller layer, but rather in the servicelayer when the database access happens. It also means that the `Optional<...>` method signatures are going to be dropped where the exceptions are thrown for a proper http status feedback.
Exception handling can be done at the roots cause. If you proceed the validation at the Controller before code is beeing executed and you proceed the validation at the database access you get a validated code flow inbetween and do not have to worry about it anymore. But it does take discipline  to do so and keep doing it in the future.

Hopefully i explained my thoughts well enough. Otherwise i am open for discussions and would like to provide a PR you need me to do so.

**Comment by mschulte-tsi** [comment]
With the Release of 1.0.0 two Nginx were added toe the Verification server with a sidecar pattern. The Verification Server can only be accessed trough a Nginx. 
With the Nginx default maximum body size of 1Mb this atack vector should be closed

**Comment by mlaue-tech** [comment]
@anjeyy First of all - Thank you for your contribution!

> ## Expected Benefits
> 
> 1. Before even a line of code inside the controller is executed, there is a validation of the given GUID, otherwise client gets immediate error.
>
This is a good hint, which has been implemented by the linked pull request. 

> 2. Use of intended ReST architecture with specific http status codes..
> 
> 
The Codes will not be changed for now, because they have been specificated and communicated with SAP.
