### ISSUE TITLE
possible unreachable code paths in getTestState 

### ISSUE THREAD

**Issue by Danny02** [corona-warn-app/cwa-verification-server#117]
1. in the case that the session was created by a teleTan, a positive test result is always returned. why?
2. Is it not so that either a telTanHash or guidHash is set in the session? The line `String hash = appSession.get().getHashedGuid() != null ? appSession.get().getHashedGuid() : appSession.get().getTeleTanHash();` must therefore always return the hashedGuid.
3. The labService requires a HashedGuid, wouldn't it be wrong to "cast" the teleTanHash into a GuidHash?

https://github.com/corona-warn-app/cwa-verification-server/blob/1592ae2fe2792e07c95f3851906a2c05150df956/src/main/java/app/coronawarn/verification/controller/VerificationController.java#L225

**Comment by mschulte-tsi** [comment]
1. You can only revice a teleTan if you are tested positive
2. & 3. This behavior was fixed with the linked PR
