### ISSUE TITLE
Codespell report for "cwa-verification-server" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [corona-warn-app/cwa-verification-server#126]
Similar to the description in the issue [cwa-app-ios#149](https://github.com/corona-warn-app/cwa-app-ios/issues/149) there exists on [fossies.org](https://fossies.org) also a regularly updated [codespell](https://github.com/codespell-project/codespell) [report](https://fossies.org/features.html#codespell) for "cwa-verification-server":

&nbsp;&nbsp;https://fossies.org/linux/test/cwa-verification-server-master.tar.gz/codespell.html

**Comment by daniel-eder** [comment]
This is a good first issue. No programming experience is required, this issue is only about fixing typos as listed here: https://fossies.org/linux/test/cwa-verification-portal-master.tar.gz/codespell.html

Despite the simplicity, we appreciate any contributions!

**Comment by jschleus** [comment]
Fossies just found 3 new spelling errors in `docs/architecture-overview.md`, see
https://fossies.org/linux/test/cwa-verification-server-master.tar.gz/codespell.html

By the way, although in the meantime nearly superfluous there exists now on the Fossies server a regularly updated small page showing a summary of the (very few) still found codespell errors in the diverse CWA projects: https://fossies.org/linux/test/cwa_codespell_status.html

**Comment by daniel-eder** [comment]
Thank you for the update! The latest spelling errors will be fixed by #182.
