### ISSUE TITLE
[ATHENE] Create Teletan Authorization

### ISSUE THREAD

**Issue by tro-dev** [corona-warn-app/cwa-verification-server#139]
Release Version: 0.5.3

The verification server implements an API endpoint for generating a teletan ("/tan/teletan"). The documentation specifies that this should only be possible for medical employees. We could not find the authorization mechanism in the code, did we miss something or is it not yet implemented?

We just want to make sure this will be implemented, as a teletan enables an adversary to upload forged diagnosis keys to induce false positives, defeating the purpose of the system.

**Comment by dfischer-tech** [comment]
Pls check the PR Feat: JWT implementation for the teleTAN request #134 will meet the requirement.
Needs only to be reviewed and merged.

**Comment by dfischer-tech** [comment]
The merge is planned after the final infrastructure issues are ready
