### ISSUE TITLE
An attacker can generate unlimited valid TANs

### ISSUE THREAD

**Issue by selectAll** [corona-warn-app/cwa-verification-server#144]
## Description
If an attacker knows the QR code _(GUID)_ of **any** patient tested **positive** _(has an active record in testresult server)_, the attacker can generate any number of valid TANs. Using these TANs the attacker can upload fake diagnosis keys to the submission service.

The solution architecture assumes that the registration token(device identifier) is unique per GUID/teleTAN. This assumption will not hold true always. 

## Steps to reproduce the issue
![flow](https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/227925416abe431e8dcec94bc4d3ab87ff16f974/images/solution_architecture/figure_3.svg)

| Steps to reproduce | Description  | Step from figure above |
|-:|-|-|
| [1] | Patient: scans QR and sends GUID to Verification Server.<br> Valid Registration Token is persisted to phone. | 1, 2, 3 & 4 |
| [2] |Assume patient is infected with COVID. <br> Laboratory Information System: Notifies the Test Result Server information that the patient is infected. | A |
| [3] | Patient: Generates TAN using Registration Token | 9, 10, 11, 12 & 13 |
| [4] | Attacker: Sends the same GUID to Verification Server.<br> Note that the attacker get a new valid Registration Token | 2,3 & 4 |
| [5] | Attacker: Sends new Registration Token and generates a valid TAN | 9, 10, 11, 12 & 13 |
| [6] | Attacker can repeat [4] & [5] continously to obtain new TANs |  |

## Possible Fix
Gut feeling is that the issue is in [AppSessionService](https://github.com/corona-warn-app/cwa-verification-server/blob/60f33ab3f976c6461ba23c191b6420da4fd2f3d3/src/main/java/app/coronawarn/verification/service/AppSessionService.java#L159)
```
  public boolean checkRegistrationTokenAlreadyExistsForGuid(String hashedGuid) {
    log.info("Start checkRegistrationTokenAlreadyExistsForGuid.");
    VerificationAppSession appSession = new VerificationAppSession();
    appSession.setHashedGuid(hashedGuid);
    return appSessionRepository.exists(Example.of(appSession, ExampleMatcher.matchingAll()));
  }
```
After [3] the app_session table is updated with tan_counter and therefore `ExampleMatcher.matchingAll()` won't match the attacker's request from [4] and thereby returns a new registration token

Ps. Thanks for the detailed documentation of the architecture. That made it easier to report this issue.

**Comment by dfischer-tech** [comment]
Thank you very much for your analysis and detailed description. I was able to reproduce the behavior and will create a fix.
