### ISSUE TITLE
Please introduce code reviews in your development process

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-verification-server#158]
## Current Implementation

Example : TanServiceTest.java

Some tests end with test, most don‘t - test postfix is not necessary because of @Test property

retunedTan? Or should it read  returnedTan?

Very dense test code

Completeness? I.e. Where is the test case that as save is not successful?

## Suggested Enhancement

This should be introduced after the first release but then rather quickly

Introduce coding standards and verify them with code reviews.

I.e. introduce block comments in test cases  for preparation, test, verification
I.e. make clear what is the object under test. In the file TanServiceTest.java I would not use the name tanService but the generalized name objectUnderTest. This is especially useful if more than one object of a class is created but only one is under test.

## Expected Benefits

Better maintainable code
Higher quality in the long run

**Comment by M-Abdelbaset** [comment]
Hello @daniel-eder @ascheibal . What's the status of this issue? Can I take it?

**Comment by daniel-eder** [comment]
@M-Abdelbaset My apologies, the issue has gone unnoticed as we were working on higher priority topics for the next release. I will bring it up in our daily meeting. That said, we, of course, invite you and any other community member to review our code and raise issues or PRs for specific improvements, such as those mentioned by HolgerMayer.

**Comment by matsmad** [comment]
Would also be happy to assist you on code reviews.
Feel free to contact me.

**Comment by mschulte-tsi** [comment]
Code reviews are already part of the process. If you have a specific issue you want to address, we would be happy to review your PR.
