### ISSUE TITLE
Do TAN's loose validity over time?

### ISSUE THREAD

**Issue by AlptraumSAP** [corona-warn-app/cwa-verification-server#168]
Scenario:
Terrorists do collect TAN's. Then they try to mark as many people as possible, using own-made emulators of the app, before it gets registered.
Conclusion:
To stem this, the timespan for entering the TAN should be limited.

**Comment by MariusE** [comment]
@AlptraumSAP from the documentation:
https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#core-entities

>  **The lifetime of a teleTAN is 1h.**

**Comment by mlaue-tech** [comment]
@MariusE @AlptraumSAP 

And the lifetime of a TAN is 14 days.

**Comment by MariusE** [comment]
Thanks, @mlaue-tech ! :)
I totally missed the section with the timeframes, at the end of the docs:

https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#used-timeframes

**Comment by daniel-eder** [comment]
The lifetime of the TANs has been clarified I am therefore closing the issue. If there are further questions please open a new issue.
