### ISSUE TITLE
FakeRequestService uses fakeTanDelay for all fake endpoint requests

### ISSUE THREAD

**Issue by ddewaele** [corona-warn-app/cwa-verification-server#199]
## Describe the bug

In the `FakeRequestService` I noticed that `generateTan`, `generateRegistrationToken` and `getTestState` all use the `fakeTanDelay` to schedule a fake response, despite the availability of a `fakeTokenDelay` and `fakeTestDelay`

## Expected behaviour

The appropriate delays should be implemented for the various fake endpoint requests

## Possible Fix

See expected behaviour

## Additional context

N/A

**Comment by mschulte-tsi** [comment]
@ddewaele Thank you verry much for noticing and analysing this bug. Your attention to this detail was very helpful, we will implement the fix.
