### ISSUE TITLE
fix: Update updated_at upon tan creation

### ISSUE THREAD

**Issue by ascheibal** [corona-warn-app/cwa-verification-server#210]
## Describe the bug

The updated_at property will only be set once upon data creation, never be updated

## Expected behaviour

property 'updated_at' shall be updated, upon tan generation.

## Steps to reproduce the issue

created_at only be touched once, upon dataset creation

## Technical details

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix

write appSession.updatedAt upon tan generation

## Additional context

**Comment by dfischer-tech** [comment]
@ascheibal I think this is already resolved by:
https://github.com/corona-warn-app/cwa-verification-server/pull/214

**Comment by mschulte-tsi** [comment]
Was closed with #214
