### ISSUE TITLE
Issue when starting the application locally

### ISSUE THREAD

**Issue by chrisbartoloburlo** [corona-warn-app/cwa-verification-server#277]
## Your Question

When running `java -jar target/cwa-verification-server-1.5.0-SNAPSHOT.jar` (as in the documentation) I get the following error: 
`no main manifest attribute, in target/cwa-verification-server-1.5.0-SNAPSHOT.jar`. Am I doing something wrong?

**Comment by LucasTelekom** [comment]
Thank you very much for the advice.

The README.md (documentation) has been adapted accordingly. 
By adding "**--spring.profiles.active=local**" to the already known command, the error should now be solved. 
Therefore, the server can be started with following commands: "mvn package",
"java -jar target/cwa-verification-server-0.0.1-SNAPSHOT.jar **--spring.profiles.active=local**".
