### ISSUE TITLE
Question on issue

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-verification-server#281]
## Your Question

Hey there, there was an issue concerning this repository opened in the documentation repository today. The issue was deleted shortly afterwards. Will you look into the details, which were shared in the documentation issue, & address the reported problem?

cc @thomasaugsten (I guess it was you who deleted the issue)

Please note that I'm keeping this issue very general on purpose and that you don't have to answer in detail, but just "Yes, we're looking into it" or "No, we don't". I just want to make sure that the issue is not forgotten after it was deleted.

**Comment by thomasaugsten** [comment]
I recreated the issue and the developer of the verification server will give a statement
