### ISSUE TITLE
teleTAN generation and spec don't match. 

### ISSUE THREAD

**Issue by theodiefenthal** [corona-warn-app/cwa-verification-server#54]
According to the architecture-overview, the teleTAN consists out of digits and uppercase letters only, in the code, one can see that it consists of digits, uppercase and lowercase letters. The implementation might be disadvantegeous when communicating the TAN over something like the phone, but increases security in terms of brute force attacks guessing a tan.

**Comment by ascheibal** [comment]
To be discussed with  architecture Team. Indeed, from the perspective of smartphone keyboards usage, it might be even better to only use lowercase letters to ease input.

**Comment by martinmuellerrohde** [comment]
Thus should be fixed by #119 already.
Grüße you can close thus issue now.

**Comment by daniel-eder** [comment]
Fixed in #119
