### ISSUE TITLE
Move GitHub specific files to .github folder

### ISSUE THREAD

**Issue by CCFenner** [corona-warn-app/cwa-verification-server#64]
## Current Implementation

Currently the project root contains some files that are only relevant for Github.

## Suggested Enhancement

To maintain a cleaner code repository I suggest to move the GitHub specific files to the `.github` folder.

**affected files:**
- `CODEOWNERS`
- `CONTRIBUTING.md`
- `CODE_OF_CONDUCT.md`
- ...?

## Expected Benefits

Better overview in the repository and local IDE.

**Comment by kreincke** [comment]
@CCFenner Many thanks for your review(s). You did a lot of work during the last days. Very helpful.

Nevertheless, in this case, we do not want 'hide' these documents in a hidden directory. Moreover, we want everyone who downloads the repo or browses it using GitHub, to know that we have contributing rules and a code of conduct, etc. So, we decided to set up each corona-warn-up repo with a specific set of 'health' files. You will see, that the repos primarily managed by SAP have the same structure of 'health' files as the repos primarily managed by DT.
Best regards KR
