### ISSUE TITLE
Pull requests fail during deploy step 

### ISSUE THREAD

**Issue by martinmuellerrohde** [corona-warn-app/cwa-verification-server#67]
## Describe the bug

Even cosmetic PRs like #63 fail during the ci/build check due to an attempt to deploy the successful build:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project cwa-verification-server: Failed to deploy artifacts: Could not transfer artifact app.coronawarn.verification:cwa-verification-server:jar:0.3.2-20200526.063523-31 from/to github (https://maven.pkg.github.com/corona-warn-app/cwa-verification-server): Authorization failed for https://maven.pkg.github.com/corona-warn-app/cwa-verification-server/app/coronawarn/verification/cwa-verification-server/0.3.2-SNAPSHOT/cwa-verification-server-0.3.2-20200526.063523-31.jar 403 Forbidden -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
##[error]Process completed with exit code 1.`

## Expected behaviour

Pull requests should go through the build pipeline including all code verification and unit tests but skip the deploy step

## Steps to reproduce the issue

See #65 

https://github.com/corona-warn-app/cwa-verification-server/pull/65/checks?check_run_id=708323706

**Comment by martinmuellerrohde** [comment]
@jhagestedt just made a fix in #66 for this

**Comment by jhagestedt** [comment]
yep give me a second

**Comment by martinmuellerrohde** [comment]
Thanks for the quick fix @jhagestedt !
But now it fails with Sonar:

`[WARNING] Unable to analyse file 'pom.xml'.
java.lang.IllegalStateException: You're not authorized to run analysis. Please contact the project administrator.
	at org.sonar.scanner.scan.filesystem.MetadataGenerator.setMetadata(MetadataGenerator.java:55)
	at org.sonar.scanner.scan.filesystem.FileIndexer.lambda$indexFile$0(FileIndexer.java:127)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkMetadata(DefaultInputFile.java:77)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.charset(DefaultInputFile.java:216)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.contents(DefaultInputFile.java:101)`
.....
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project cwa-verification-server: null: MojoExecutionException: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
##[error]Process completed with exit code 1.`
