### ISSUE TITLE
Pull requests fail during Sonar step

### ISSUE THREAD

**Issue by martinmuellerrohde** [corona-warn-app/cwa-verification-server#69]
## Describe the bug

Pull requests fail during mvn sonar step:

`[WARNING] Unable to analyse file 'pom.xml'. java.lang.IllegalStateException: You're not authorized to run analysis. Please contact the project administrator. at org.sonar.scanner.scan.filesystem.MetadataGenerator.setMetadata(MetadataGenerator.java:55) at org.sonar.scanner.scan.filesystem.FileIndexer.lambda$indexFile$0(FileIndexer.java:127) at org.sonar.api.batch.fs.internal.DefaultInputFile.checkMetadata(DefaultInputFile.java:77) at org.sonar.api.batch.fs.internal.DefaultInputFile.charset(DefaultInputFile.java:216) at org.sonar.api.batch.fs.internal.DefaultInputFile.contents(DefaultInputFile.java:101)`
[...]
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default-cli) on project cwa-verification-server: null: MojoExecutionException: NullPointerException -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException ##[error]Process completed with exit code 1.`

## Expected behaviour

Pull requests should go through the build pipeline including all code verification and unit tests but either skip the sonar step or necessary authorization needs to be provided to succeed (later preferred)

## Steps to reproduce the issue

See #65 

https://github.com/corona-warn-app/cwa-verification-server/pull/65/checks?check_run_id=708392877

**Comment by zhedar** [comment]
I had also retriggered #63 after #66 with the same result.

Also see https://stackoverflow.com/a/39720346/1644440 for why this might happen. According to the answer having analysis on every pull request might not be preferrable. I'm not sure how other big projects deal with that though as you probably want to have some quality check on outside PRs.

**Comment by jhagestedt** [comment]
I disabled sonar for PRs now.
Will try to figure out if its possible to bring it back again later.
