### ISSUE TITLE
Decide for either CRLF or LF line endings and add .gitattributes file

### ISSUE THREAD

**Issue by martinmuellerrohde** [corona-warn-app/cwa-verification-server#80]
## Current Implementation

Because this repo doesn't contain a `.gitattributes` file, line endings differ from contributor to contributor causing unwanted diffs in checkins.

## Suggested Enhancement

Add `.gitattributes` file to this repo and decide wether you prefer Windows-style CRLF or Unix-style LF line endings.

See https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings how to do this.

I suggest to add the follwing lines to `.gitattributes`:

```
*.java text eol=lf
*.yml text eol=lf
```

## Expected Benefits

Fewer diffs when contributing a pull request and easier to read history.

**Comment by dfischer-tech** [comment]
Normally this problem should not arise if everyone uses editorconfig correctly.

**Comment by martinmuellerrohde** [comment]
I think git decides at commit time if and how to convert.
It's not depending in your IDE.
